hagenw/sphinxcontrib-katex

.gitignore, README.rst, setup.py, sphinxcontrib/katex.py
Hi! I was having some trouble with the auto-render functionality, and it seemed like it was because the js was loaded before the body rather than after. The KaTeX auto-render readme suggests wrapping in a function that loads when the DOM is finished loading: https://github.com/Khan/KaTeX/tree/master/contrib/auto-render#usage
I also added a new configuration option for more general KaTeX configuration, and made the version a configurable variable. Please let me know any further changes or if you want me to drop any of these changes.
=> Fix autorender

README.rst, sphinxcontrib/katex.py
Changes are:
* document all available options
* remove the `katex_macros` option as it is already part of `katex_options`
* automatically set the delimiters for the KaTeX auto-renderer
=> Enhance handling of KaTeX options

README.rst, sphinxcontrib/katex.py
Hi,
Some of the changes added to 0.2.0 caused a bug if `katex_options` was blank.
I'm also curious why the delimiters are hard-coded and cannot be configured? There could be a case where a user wants to add some additional delimiters (for instance, if they have any raw text with math they want to format).
=> Fix options bug

sphinxcontrib/katex.py
The structure of math-related nodes has changed in Sphinx 1.8.0, from being something like:
```xml
<displaymath latex="f(x) = x^2" />
```
to:
```xml
<math_block>f(x) = x^2</math_block>
```
While there appears to be some sort of workaround to enable the current usage present in Sphinx 1.8.0, (https://github.com/sphinx-doc/sphinx/blob/16533cff9a1e20fc10ec78eaf7c4796cd3552965/sphinx/addnodes.py#L203)
it doesn't seem to actually work and the following traceback occurs:
```
Traceback (most recent call last):
File ".../site-packages/sphinx/cmd/build.py", line 304, in build_main
app.build(args.force_all, filenames)
File ".../site-packages/sphinx/application.py", line 341, in build
self.builder.build_update()
File ".../site-packages/sphinx/builders/__init__.py", line 347, in build_update …
```
=> Handle change in math node structure in Sphinx 1.8.0

requirements.txt, sphinxcontrib/katex.py
Sphinx deprecated the `sphinx.ext.mathbase.setup_math` function in 1.8 and replaced it by `	add_html_math_renderer`.
This means we have also to increase our sphinx dependency to be `>=1.8`.
=> Remove deprecated sphinx.ext.mathbase.setup_math

doc/index.rst
Adds an example usage to the documentation start page and hides the TOC instead.
=> Add KaTeX example to index

.travis.yml, CONTRIBUTING.rst, doc/requirements.txt, tests/index.rst
As some functionality that we want to use in the actual documentation is only available in newer sphinx versions, we test only a sub set of the documentation for older versions of sphinx.
This way we don't have to drop support for those versions yet.
=> TST: add stripped down test for sphinx<=1.8

doc/examples.rst
This adds a few equations with equation numbers in the documentation.
It will provide a good test bed for checking the `:nowrap:` math option.
=> DOC: add equation number example

MANIFEST.in
In `MANIFEST.in` it was still `doc/` included and not `docs/`.
=> Fix inclusion of docs/ into PyPI package

sphinxcontrib/katex.py
Fixes #29.
It adds the current environment to `Popen` and changes the katex command name to `katex.cmd` under Windows.
=> Fix running katex command under windows

docs/examples.rst, sphinxcontrib/katex-math.css
Succeeds #33 
Adds another example to the docs and fixes the cropping by adding 1px padding to the top and bottom.
=> Fix cropping of equation on the top or bottom

sphinxcontrib/katex.py
Closes #38 
This replaces the usage of `add_stylesheet` and `add_javascript` by `add_css_file` and `add_js_file`.
=> Fix add_css() and add_js() for Sphinx 4.0

sphinxcontrib/katex.py
Running sphinx with having KaTeX pre-rendering enabled was always succesful even when KaTeX failed with an error message.
The code now checks if KaTeX succeeds and throws a RuntimeError with the original error message otherwise.
=> Let pre-rendering fail if KaTeX fails

docs/index.rst, sphinxcontrib/katex.py
Switch to KaTeX 0.13.11 and fix related macro definition errors.
=> Use KaTeX 0.13.11

setup.cfg
As those Python versins are no longer supported by `pip` we drop them here as well.
=> Remove support for Python 2.7, 3.4, 3.5

setup.cfg
We test already for Python 3.9, but we haven't added it to `setup.cfg`.
=> Add support for Python 3.9

.github/workflows/katex.yml, README.rst
In the documentation we also have to update the KaTeX version we use as there is no way to include this automatically.
I also restricted the KaTeX pre-rendering test to use the same KaTeX version.
=> Use KaTeX 0.13.11 in docs and all tests

setup.cfg
Changes `name1-name2` to `name1_name2` as `setuptools` was complaining about this.
=> Update metadata definitions in setup.cfg

setup.cfg
The version of the release `v0.8.0` was set to `0.0.0` as it was not included in `setup.cfg`.
=> Fix missing version in setup.cfg

.github/workflows/linkcheck.yml
As we cannot build the pages for the release 0.8.0 we disable the linkchecks for now.
=> TST: disable linkcheck

setup.cfg
There was still a typo in `setup.cfg`. This solution I tested now locally and it resulted in the correct version number.
=> Fix reading of version in setup.cfg

MANIFEST.in
Compiling the docs on RTD is not able to find the CSS file.
Try to fix this by readding the `MANIFEST.in` file again.
=> Readd manifest to fix compilation of latest docs

.github/workflows/linkcheck.yml
As the documentation builds are working again on RTD we can re-enable checking for broken links.
=> TST: re-enable link checks

sphinxcontrib/katex-math.css
This increases the top padding of equations from `1px` to `3px` in order to change
to
See also the discussion in https://github.com/hagenw/sphinxcontrib-katex/pull/33
=> Increase top padding of equations

sphinxcontrib/katex.py
The output from katex when pre-rendering can contain a trailing newline, which gets included in the resulting html. This causes an additional space after an inline equation, which is mostly noticeable for equations just before a comma/period.
As an example, this is the result on the inline math snippet from the documentation:
* `katex_prerender = True`, before:
* `katex_prerender = True`, after:
* `katex_prerender = False`:
This fix simply strips all trailing newlines from the katex output.
=> Remove unintentional whitespace in prerender mode

setup.cfg
Closes #63.
Removes the Sphinx<4.0.0 limit from `setup.cfg`.
=> Allow sphinx>=4.0.0 in setup.cfg

.github/workflows/sphinx.yml
Newer versions of `docutils` do not work with older sphinx versions, compare https://github.com/hagenw/sphinxcontrib-katex/runs/4950940111?check_suite_focus=true
=> CI: use docutils<0.17 for old sphinx versions

README.rst, docs/configuration.rst, docs/index.rst, docs/installation.rst, docs/macros.rst, docs/usage.rst
Add a badge to the README listing supported Python versions and linking to pypi.org.
=> DOC: add Python version badge

README.rst
The test badge was still showing results from Travis CI, but we are now using Github Actions for the tests.
=> DOC: adjust test badge to point to Github Actions

.github/workflows/katex.yml, README.rst, sphinxcontrib/katex.py
Uses https://github.com/KaTeX/KaTeX/releases/tag/v0.16.0 as new default.
=> Use KaTeX 0.16.0

CONTRIBUTING.rst, update-katex-version.sh
Closes #79 
This adds a script for updating to a newer KaTeX version.
Execute the script with:
```bash
$ bash update-katex-version.sh
```
in the root of the repo and if a newer version can be found it will
* download `sphinxcontrib/katex.min.js`
* download `sphinxcontrib/auto-render.min.js`
* update the version number in `sphinxcontrib/katex.py`
* update the version number in `README.rst`
=> Add script to update KaTeX version

README.rst, docs/configuration.rst, docs/installation.rst, docs/macros.rst, docs/usage.rst
For the new server side pre-rendering introduced in (https://github.com/hagenw/sphinxcontrib-katex/pull/69) we no longer have to install `katex` using `npm`, but just require that `nodejs` is available.
=> DOC: fix instructions for pre-rendering

sphinxcontrib/katex-math.css
Before it could happen that we match not very well the font size of the rest of the HTML page, e.g.
this changes this by requiring the same font size
=> Make sure we use font-size of document

sphinxcontrib/katex-math.css
The change introduced in #87 was not applied to all HTML elements.
=> Fix change in font-size

.github/workflows/katex.yml, .github/workflows/linkcheck.yml, .github/workflows/os.yml, .github/workflows/publish.yml, .github/workflows/python.yml, .github/workflows/sphinx.yml
We have deprecated actions, compare https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To fix I switched to
* actions/checkout@v3
* actions/setup-node@v3
* actions/setup-python@v4
=> TST: update versions of used Actions

sphinxcontrib/katex-math.css
As written in the [KaTeX docs](https://katex.org/docs/font.html) it is on purpose that the math font size is 1.21 times larger:
So I think we shouldn't enforce a different behavior here. if the user wants a different behavior she/he has to write custom CSS.
=> Revert smaller scaling of math font

.github/workflows/flake8.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, docs/conf.py, setup.cfg, sphinxcontrib/katex.py
This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.
=> TST: use pre-commit for flake8 checks

sphinxcontrib/katex.py
timeout_error is called multiple times with the class context; arguably could leave it as static method and remove the cls. prefix from the other calls but keeping conservative.
Fixes #98
=> Convert timeout_error to classmethod

README.rst
Fixes a small typo in the usage documentation:
=> DOC: fix typo in usage section

docs/_static/custom.css, docs/conf.py
This tweaks the HTML sphinx theme by reducing the color saturation for:
* horizontal separation lines as in the footer and topbar
* code highlight blocks
* text in footer
* background of sidebar
In addition, it removes the source link from the footer and the "General Index" entry from the sidebar.
=> DOC: reduce gray color saturation of HTML theme

docs/_static/custom.css
Make sure external links show an underline when hovered by the mouse.
=> DOC: ensure hovered links show underline

docs/_static/custom.css
Ensure RTD sidebar is shown in theme colors:
=> DOC: style RTD sidebar

docs/_static/custom.css
This reverts back to the original colored RTD sidebar:
=> DOC: use original RTD sidebar

README.rst, docs/configuration.rst, docs/index.rst, docs/installation.rst, docs/macros.rst, docs/usage.rst
In https://github.com/hagenw/sphinxcontrib-katex/pull/42 we split up the tests into several Github actions, which means it makes no longer sense to show a single test badge (and the current test badge was still pointing to the removed "Test" action).
This pull request simply removes the badge from the README.
=> DOC: remove test badge

docs/_static/custom.css
This reverts commit 3eb32df89dd9b9367201aa7642810dde323459b4.
After comparing both solutions, I decided to stay with the one of release v0.9.6.
=> DOC: revert use original RTD sidebar

.github/workflows/python.yml, setup.cfg
Python 3.7 has reached its [end of life](https://endoflife.date/python) at 2023/06/27, so we remove support for it.
=> Remove support for Python 3.7

.github/workflows/katex.yml, .github/workflows/linkcheck.yml, .github/workflows/linter.yml, .github/workflows/os.yml, .github/workflows/publish.yml, .github/workflows/sphinx-legacy.yml, .github/workflows/sphinx.yml, .pre-commit-config.yaml, update-katex-version.sh
* Updates all github Actions that use a single Python version to use Python 3.10
* Updates the nodejs version to 20.0
* Extends `update-katex-version.sh` script to also update the KaTeX version in `.github/workflows/katex.yml`
* Update sphinx version to 5.* for all tests that use a fixed sphinx version and Python 3.10
* Expand tested sphinx versions by 5.3.0
* Split sphinx action into two as old versions of sphinx require Python 3.8
=> CI: use Python 3.10 as default version

.github/workflows/sphinx.yml
This adjusts the sphinx tests to also test for versions 6.2.1 and 7.* and no longer restrict the requirements on `jinja2` and `docutils`.
=> TST: test for sphinx versions 6.2.1, 7.*

.readthedocs.yaml, update-katex-version.sh
As Read The Docs now requires configuration files in order to build the docs, we add one.
We also enable pre-rendering with it and extend `update-katex-version.sh` to also update the used KaTeX version inside the RTD config file.
=> DOC: add read the docs configuration

.readthedocs.yaml
In the RTD config file we had disabled the usage of the config file. This pull request re-enables the config file to select the desired theme for the documentation.
=> DOC: ensure RTD build uses config file

.github/workflows/build.yml, .github/workflows/package.yml, pyproject.toml
Fix publication of Python package with `pyproject.toml`.
It also adds a test for building the Python package.
The previous configuration has failed with https://github.com/hagenw/sphinxcontrib-katex/actions/runs/6495362329/job/17640167421.
=> Fix building of Python package

.github/workflows/katex.yml
KaTeX binary is not needed for pre-rendering, `nodejs` is sufficient!
See also https://github.com/hagenw/sphinxcontrib-katex/issues/122#issuecomment-2090659302
=> CI: don't install KaTeX binary

update-katex-version.sh
As we removed installing KaTeX in the action to test the pre-rendering in #124, we also do no longer need to update the Action definition, when using another version of KaTeX.
=> Version number update in Action no longer needed

.github/workflows/documentation.yml, .github/workflows/katex.yml, .github/workflows/linkcheck.yml, .github/workflows/linter.yml, .github/workflows/os.yml, .github/workflows/package.yml, .github/workflows/publish.yml, .github/workflows/python.yml, .github/workflows/sphinx-legacy.yml, .github/workflows/sphinx.yml
As discussed at https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/, we need to update all Github Actions that are still using Node.js 16.
We fix this here by updating to:
* actions/checkout@v4
* actions/cache@v4
* actions/setup-node@v4
* actions/setup-python@v5
* softprops/action-gh-release@v2
=> CI: update actions to switch to Node.js 20

.github/workflows/katex.yml, pyproject.toml, sphinxcontrib/katex-server.js, sphinxcontrib/katex.py, tests/requirements.txt, tests/test_katex_server.py
Relates to #122 
This uses the value from `katex_js_path` for the path to the KaTeX executable, used inside ` katex-server.js` to render the pages in pre-render mode. The default value of `katex_js_path` points to the KaTeX Javascript library bundled with this extension, but the user can point to another file on the local machine.
=> Use katex_js_path when pre-rendering

.github/workflows/python.yml, .github/workflows/sphinx-legacy.yml, pyproject.toml
Remove support for Python 3.8 as it has reached its end of life, and remove all tests as we also no longer have runner available.
=> Remove support for Python 3.8

pyproject.toml
Ensure `python_requires` matches the actual required Python version.
=> Set python_requires >=3.9

.github/workflows/linkcheck.yml, .readthedocs.yaml, docs/conf.py
Follows https://github.com/astral-sh/uv/issues/10074 to update the Read The Docs config file to work with `uv` instead of `pip`.
=> CI: update RTD config to support uv

sphinxcontrib/katex-math.css
Closes https://github.com/hagenw/sphinxcontrib-katex/issues/134
The proposed fix changes
to
for the widely used `pydata-sphinx-theme`.
=> Fix eq center alignment for pydata-sphinx-theme
