- README.rst
- sphinxcontrib/katex.py
This implements option 1.) from #6.
> Allow for user defined autorendering delimiters

- .travis.yml
- CONTRIBUTING.rst
- README.rst
- doc/conf.py
- doc/configuration.rst
- doc/macros.rst
- sphinxcontrib/katex.py
> Serverside pre-rendering

- README.rst
- doc/conf.py
- sphinxcontrib/katex.py
Update KaTeX version and remove obsolete `katex_version` entry in `doc/conf.py`
> Switch to Katex 0.10.2

- NEWS.rst
- doc/conf.py
- doc/index.rst
... and a few minor tweaks on the documentation.
> Switch to Keep a Changelog format

- NEWS.rst
As we have only a few changelog entries I removed the subsections and use the wordings `Added`, ... directly in the bullet points.
> DOC: make NEWS shorter

- README.rst
- doc/configuration.rst
- doc/index.rst
- doc/installation.rst
- doc/macros.rst
- doc/usage.rst
Add badges for tests, documentation, and license.
> DOC: add badges to README

- .travis.yml
Just a test if the global `env` setting works together with `matrix`. This would allow easier syntax for the `$FOLDER` default value.
> TST: simplify command by global env variable

- .github/workflows/os.yml
Add tests for Windows and macOS.
> TST: add Windows and macOS

- CONTRIBUTING.rst
- setup.cfg
- setup.py
- sphinxcontrib/__init__.py
Before I tried to introduce getting the version number automatically, but I couldn't figure out how to use it with a namespace package, so we stay with defining it manually.
> Fix declaration of namespace package

- .github/workflows/katex.yml
There was a typo in the definition file.
> TST: fix KaTeX pre-rendering test definition

- .github/workflows/katex.yml
test that pre-rendering with KaTeX also works on Windows and macOS.
> TST: run pre-rendering on Windows and macOS

- docs/conf.py
- sphinxcontrib/katex.py
> DOC: update copyright year

- docs/conf.py
- sphinxcontrib/katex.py
Update copyright year in docs and main code file.
> Update copyright year

- .github/workflows/python.yml
- setup.cfg
Add support for Python 3.10 by adding tests and mention it in `setup.cfg`.
> Support Python 3.10

- README.rst
> DOC: fix typo in usage section

- .github/workflows/python.yml
- setup.cfg
Add official support for [Python 3.11](https://docs.python.org/3/whatsnew/3.11.html)
> Add support for Python 3.11

- .github/workflows/katex.yml
- .github/workflows/linkcheck.yml
- .github/workflows/os.yml
- .github/workflows/python.yml
- .github/workflows/sphinx.yml
Use `main` as name for default branch in tests
> CI: use main as default branch

- .github/workflows/publish.yml
Updates the following Guithub Action:
* `actions/create-release@v1` -> `softprops/action-gh-release@v1`
> CI: update Github actions

- .github/workflows/katex.yml
Upgrade pre-render test to use latest Node version.
> TST: ugrade to Node 16

- docs/_static/custom.css
Updates theme colors, especially sidebar and footer based on https://hydra.cc/docs
> DOC: update theme colors

- docs/_static/custom.css
Decrease font size and line height of footer:
> DOC: decrease footer size

- .github/workflows/python.yml
- setup.cfg
Add tests and support for Python 3.12.
> Add support for Python 3.12

- .readthedocs.yaml
> DOC: fix building docs on RTD

- CHANGELOG.rst
- sphinxcontrib/katex.py
> Release 0.9.10
